# Generated by Django 3.2.5 on 2021-08-08 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rid', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('ftype', models.CharField(max_length=100)),
                ('dim', models.PositiveIntegerField()),
                ('serialno', models.CharField(max_length=1000)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cdimension', models.PositiveIntegerField()),
                ('ftype', models.CharField(max_length=100)),
                ('camount', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('vnum', models.CharField(max_length=100)),
                ('ftype', models.CharField(max_length=100)),
                ('requesterid', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('comm', models.CharField(max_length=1000)),
                ('status', models.PositiveIntegerField()),
                ('mread', models.PositiveIntegerField()),
                ('ret', models.PositiveIntegerField()),
                ('approverid', models.CharField(max_length=1000)),
                ('issueid', models.CharField(max_length=1000)),
                ('retid', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cdimension', models.PositiveIntegerField()),
                ('ftype', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('cnumber', models.PositiveIntegerField()),
                ('rate', models.FloatField(blank=True)),
                ('totalamount', models.FloatField(blank=True)),
                ('unit', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('uhead', models.CharField(max_length=100)),
                ('capprover', models.CharField(max_length=100)),
                ('aptype', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vid', models.BigAutoField(primary_key=True, serialize=False)),
                ('vnum', models.CharField(max_length=100)),
                ('vtype', models.CharField(max_length=100)),
                ('imile', models.PositiveIntegerField()),
                ('asunit', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
                ('ftype', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('vnum', models.IntegerField(default=0)),
                ('pic', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
