# Generated by Django 3.2.5 on 2021-08-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_profile_vnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
