# Generated by Django 3.2.5 on 2021-08-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210808_0518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Transaction',
        ),
    ]
