# Generated by Django 3.2.5 on 2021-08-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_transaction_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='serialno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
