# Generated by Django 3.2.5 on 2021-08-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_transaction_serialno'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
