# Generated by Django 3.2.5 on 2021-08-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_coupons_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='transamount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
