# Generated by Django 3.2.5 on 2021-08-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_vehicle_tankcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='tankcat',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
