# Generated by Django 3.2.5 on 2021-08-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_requests_tankcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='marketrate',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
