# Generated by Django 3.2.5 on 2021-08-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_transaction_marketrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='stockopen',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
