# Generated by Django 3.2.5 on 2021-08-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
