# Generated by Django 3.2.5 on 2021-08-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(default='uploads/default-avatar.png', null=True, upload_to='uploads/'),
        ),
    ]
