# Generated by Django 3.2.5 on 2021-08-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='total',
            field=models.PositiveIntegerField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='transamount',
            field=models.PositiveIntegerField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='requests',
            name='mread',
            field=models.PositiveIntegerField(max_length=1000000),
        ),
    ]
