# Generated by Django 3.2.5 on 2021-09-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20210818_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tnum', models.CharField(max_length=100)),
                ('transdetail', models.CharField(max_length=1000)),
                ('transamount', models.CharField(max_length=100)),
                ('transtatus', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
