# Generated by Django 3.2.5 on 2021-09-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_couponbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponbatch',
            name='serial_end',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='couponbatch',
            name='serial_start',
            field=models.CharField(max_length=100),
        ),
    ]
