# Generated by Django 3.2.5 on 2021-09-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20210920_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponbatch',
            name='ftype',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponbatch',
            name='unit',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
