# Generated by Django 3.2.5 on 2021-09-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20210929_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='book_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
