# Generated by Django 3.2.5 on 2021-10-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_coupons_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponbatch',
            name='creator',
            field=models.CharField(default='bfoon', max_length=1000),
            preserve_default=False,
        ),
    ]
