# Generated by Django 3.2.5 on 2021-10-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_couponbatch_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='fueldump',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lnum', models.CharField(max_length=1000)),
                ('ftype', models.CharField(max_length=100)),
                ('dim', models.PositiveIntegerField()),
                ('used', models.PositiveIntegerField()),
                ('book_id', models.CharField(max_length=100)),
                ('trans_id', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateField(auto_now=True)),
            ],
        ),
    ]
