# Generated by Django 3.2.5 on 2021-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_fueldump'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueldump',
            name='unit',
            field=models.CharField(default='Programme', max_length=100),
            preserve_default=False,
        ),
    ]
