# Generated by Django 3.2.5 on 2021-10-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_fueldump_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueldump',
            name='book',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
