# Generated by Django 3.2.5 on 2021-10-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_fueldump_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueldump',
            name='book_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fueldump',
            name='lnum',
            field=models.PositiveIntegerField(),
        ),
    ]
