# Generated by Django 3.2.5 on 2021-10-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20211001_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueldump',
            name='trans_id',
            field=models.PositiveIntegerField(),
        ),
    ]
