# Generated by Django 3.2.5 on 2021-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_fueldump_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueldump',
            name='transac',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
