# Generated by Django 3.2.5 on 2021-10-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_fueldump_transac'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='maxserialno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
