# Generated by Django 3.2.5 on 2021-10-03 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_transaction_maxserialno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueldump',
            name='transac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.requests'),
        ),
    ]
