# Generated by Django 3.2.5 on 2021-10-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_fueldump_transac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueldump',
            name='transac',
            field=models.CharField(max_length=100),
        ),
    ]
