# Generated by Django 3.2.5 on 2021-10-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_fueldump_transac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueldump',
            name='book',
        ),
        migrations.AddField(
            model_name='couponbatch',
            name='book',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fueldump',
            name='bookref',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.couponbatch'),
            preserve_default=False,
        ),
    ]
