# Generated by Django 3.2.5 on 2021-10-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20211003_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponbatch',
            old_name='book',
            new_name='bookref',
        ),
        migrations.RemoveField(
            model_name='fueldump',
            name='bookref',
        ),
    ]
