# Generated by Django 3.2.5 on 2021-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_fueldump_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponbatch',
            name='bookref',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fueldump',
            name='book_id',
            field=models.CharField(max_length=1000),
        ),
    ]
