# Generated by Django 3.2.5 on 2021-10-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_auto_20211004_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=1000)),
                ('desc', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateField(auto_now=True)),
            ],
        ),
    ]
