# Generated by Django 3.2.5 on 2021-10-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_fueldump_datemodified'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponbatch',
            name='bdel',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fueldump',
            name='ldel',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
