# Generated by Django 3.2.5 on 2021-10-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_auto_20211018_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueldump',
            name='datemodified',
            field=models.DateField(auto_now=True),
        ),
    ]
