# Generated by Django 3.2.5 on 2021-10-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_couponbatch_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponbatch',
            name='book_id',
            field=models.PositiveIntegerField(),
        ),
    ]
