# Generated by Django 3.2.5 on 2022-02-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_remove_fueldump_ldel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sign',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
