# Generated by Django 3.2.5 on 2022-02-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_alter_transaction_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uploadedFile',
            field=models.FileField(blank=True, default='0', null=True, upload_to='Uploaded Files/'),
        ),
    ]
