# Generated by Django 3.2.5 on 2022-02-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_activityreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='approverid',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityreport',
            name='issueid',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityreport',
            name='retid',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
