# Generated by Django 3.2.5 on 2022-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_auto_20220222_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='tid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
