# Generated by Django 3.2.5 on 2022-02-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_activityreport_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='litre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
