# Generated by Django 3.2.5 on 2022-02-22 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_activityreport_litre'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='cdimension',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityreport',
            name='datemodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='ftype',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
