# Generated by Django 3.2.5 on 2022-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_auto_20220222_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='bookref',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityreport',
            name='comm',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityreport',
            name='note',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
