# Generated by Django 3.2.5 on 2022-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_auto_20220223_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='bookref_s',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
