# Generated by Django 3.2.5 on 2022-03-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_activityreport_bookref_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='litre',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='mread',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='transamount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='mread',
            field=models.PositiveIntegerField(),
        ),
    ]
