# Generated by Django 3.2.5 on 2022-03-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_auto_20220305_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='sign',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
