# Generated by Django 3.2.5 on 2022-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_activityreport_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='fconsumption',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
