# Generated by Django 3.2.5 on 2022-03-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_activityreport_fconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponbatch',
            name='rbal',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
