# Generated by Django 3.2.5 on 2022-03-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='Country',
            new_name='country',
        ),
    ]
