# Generated by Django 3.2.5 on 2022-03-28 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_rename_country_settings_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='datemodified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.CharField(default='coupon system', max_length=100),
            preserve_default=False,
        ),
    ]
