# Generated by Django 3.2.5 on 2022-04-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_auto_20220328_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='sign',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
