# Generated by Django 3.2.5 on 2022-04-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_alter_activityreport_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='appurl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
