# Generated by Django 3.2.5 on 2022-04-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_alter_settings_appurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='credit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='credit_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='credit_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='debit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='note',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
