# Generated by Django 3.2.5 on 2022-04-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_auto_20220419_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='note',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
