# Generated by Django 3.2.5 on 2022-04-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_alter_coupons_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='note',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
