# Generated by Django 3.2.5 on 2022-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_alter_coupons_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='credit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='debit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
