# Generated by Django 3.2.5 on 2022-04-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_auto_20220420_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
