# Generated by Django 3.2.5 on 2022-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0082_alter_requests_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
