# Generated by Django 3.2.5 on 2022-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_auto_20220421_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='unit',
            field=models.CharField(default='UNDP 34 CD', max_length=100),
            preserve_default=False,
        ),
    ]
